version: '3'
services:
  python_web_django:
    container_name: python_web_django
    build:
      context: .
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
    volumes:
      - .:/app
    depends_on:
      - postgres_concert
    networks:
      - django-network

  postgres_concert:
    image: postgres:17-alpine
    container_name: postgres_concert
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - django-network
  
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - django-network
    depends_on:
      - postgres-django
  
networks:
  django-network:
    driver: bridge